# Generated by Django 4.1.1 on 2022-12-22 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorKind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='Cins')),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='Tip')),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='Tip')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('has_elevator', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Asansör Kimlik Numarası')),
                ('mount_year', models.IntegerField(verbose_name='Montaj Yılı')),
                ('load_limit', models.IntegerField(verbose_name='Kapasite(Ağırlık - kg)')),
                ('load_limit_people', models.IntegerField(verbose_name='Kapasite (Kişi - Sayı)')),
                ('velocity', models.IntegerField(verbose_name='Beyan Hız (m/sn)')),
                ('work_distance', models.IntegerField(verbose_name='Seyir Mesafesi (m)')),
                ('station_count', models.IntegerField(verbose_name='Durak Sayısı')),
                ('description', models.CharField(max_length=100, verbose_name='Açıklama')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appmain.elevatorkind', verbose_name='Cins')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appmain.elevatortype', verbose_name='Tip')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appmain.unit', verbose_name='Kurum')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=50, verbose_name='Döküman Numarası')),
                ('description', models.CharField(default='', max_length=150, verbose_name='Açıklama')),
                ('update_date', models.DateField(verbose_name='Güncelleme Tarihi')),
                ('expire_date', models.DateField(verbose_name='Sona Erme Tarihi')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appmain.documenttype', verbose_name='Döküman Tipi')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.elevator', verbose_name='Asansör')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appmain.firm', verbose_name='Firma')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appmain.unit', verbose_name='Kurum')),
            ],
        ),
    ]
